In [520]:
## Import libraries
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import re

from sklearn.naive_bayes import MultinomialNB, BernoulliNB ,GaussianNB

from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
import warnings
# Set to ignore any warnings
warnings.filterwarnings('ignore')

In [521]:
## load training data
df= pd.read_csv("train.csv")

In [522]:
df.index = df['id']

In [523]:
# Drop column 'id'
data = df.drop(columns = ['id'])

In [524]:
data.reset_index(inplace= True)

In [525]:
# Drop column 'id'
data = data.drop(columns = ['id'])

In [526]:
data['keyword'].unique()

array([nan, 'ablaze', 'accident', 'aftershock', 'airplane%20accident',
       'ambulance', 'annihilated', 'annihilation', 'apocalypse',
       'armageddon', 'army', 'arson', 'arsonist', 'attack', 'attacked',
       'avalanche', 'battle', 'bioterror', 'bioterrorism', 'blaze',
       'blazing', 'bleeding', 'blew%20up', 'blight', 'blizzard', 'blood',
       'bloody', 'blown%20up', 'body%20bag', 'body%20bagging',
       'body%20bags', 'bomb', 'bombed', 'bombing', 'bridge%20collapse',
       'buildings%20burning', 'buildings%20on%20fire', 'burned',
       'burning', 'burning%20buildings', 'bush%20fires', 'casualties',
       'casualty', 'catastrophe', 'catastrophic', 'chemical%20emergency',
       'cliff%20fall', 'collapse', 'collapsed', 'collide', 'collided',
       'collision', 'crash', 'crashed', 'crush', 'crushed', 'curfew',
       'cyclone', 'damage', 'danger', 'dead', 'death', 'deaths', 'debris',
       'deluge', 'deluged', 'demolish', 'demolished', 'demolition',
       'derail', 'der

In [527]:
keywords = []
for i in data['keyword'].values:
    keywords.append(re.sub(r'%20', ' ', str(i)))

In [528]:
keywords;

In [529]:
data['location'].unique()

array([nan, 'Birmingham', 'Est. September 2012 - Bristol', ...,
       'Vancouver, Canada', 'London ', 'Lincoln'], dtype=object)

In [530]:
data['target'].unique()

array([1, 0])

In [531]:
data['text'].unique()

array(['Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all',
       'Forest fire near La Ronge Sask. Canada',
       "All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected",
       ...,
       'Suicide bomber kills 15 in Saudi security site mosque - Reuters via World - Google News - Wall ... http://t.co/nF4IculOje',
       'Two giant cranes holding a bridge collapse into nearby homes http://t.co/STfMbbZFB5',
       'The Latest: More Homes Razed by Northern California Wildfire - ABC News http://t.co/YmY4rSkQ3d'],
      dtype=object)

r'https?://\S+|www\.\S+'

In [532]:
texts = []
for i in data['text'].values:
    # Define a list of patterns to remove
    patterns_to_remove = [r'#',r'\n\n',r'\x89Û_',r'\n',r'\x89ÛÒ',r'//',r'\x89ÛÏ',r'\x89ÛÓ']

    # Combine the patterns into a single regular expression pattern
    combined_pattern = '|'.join(patterns_to_remove)

    texts.append(re.sub(combined_pattern, ' ', str(i)))

In [533]:
data['keyword'] = keywords

In [534]:
data['text'] = texts

In [535]:
data

keyword location                                               text  \
0        nan      NaN  Our Deeds are the Reason of this  earthquake M...   
1        nan      NaN             Forest fire near La Ronge Sask. Canada   
2        nan      NaN  All residents asked to 'shelter in place' are ...   
3        nan      NaN  13,000 people receive  wildfires evacuation or...   
4        nan      NaN  Just got sent this photo from Ruby  Alaska as ...   
...      ...      ...                                                ...   
7608     nan      NaN  Two giant cranes holding a bridge collapse int...   
7609     nan      NaN  @aria_ahrary @TheTawniest The out of control w...   
7610     nan      NaN  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...   
7611     nan      NaN  Police investigating after an e-bike collided ...   
7612     nan      NaN  The Latest: More Homes Razed by Northern Calif...   

      target  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
7608       1  
7609       1  
7610       1  
7611       1  
7612       1  

[7613 rows x 4 columns]

In [536]:
train_features = ['keyword']

In [537]:
## One Hot encoding the train_fetaures
ohe = OneHotEncoder()

In [538]:
encoded = ohe.fit_transform(data[train_features])

In [539]:
# Convert the encoded result to a DataFrame (if needed)
train_1 = pd.DataFrame(encoded.toarray(), columns=ohe.get_feature_names_out(train_features))

In [540]:
train_1

keyword_ablaze  keyword_accident  keyword_aftershock  \
0                0.0               0.0                 0.0   
1                0.0               0.0                 0.0   
2                0.0               0.0                 0.0   
3                0.0               0.0                 0.0   
4                0.0               0.0                 0.0   
...              ...               ...                 ...   
7608             0.0               0.0                 0.0   
7609             0.0               0.0                 0.0   
7610             0.0               0.0                 0.0   
7611             0.0               0.0                 0.0   
7612             0.0               0.0                 0.0   

      keyword_airplane accident  keyword_ambulance  keyword_annihilated  \
0                           0.0                0.0                  0.0   
1                           0.0                0.0                  0.0   
2                           0.0                0.0                  0.0   
3                           0.0                0.0                  0.0   
4                           0.0                0.0                  0.0   
...                         ...                ...                  ...   
7608                        0.0                0.0                  0.0   
7609                        0.0                0.0                  0.0   
7610                        0.0                0.0                  0.0   
7611                        0.0                0.0                  0.0   
7612                        0.0                0.0                  0.0   

      keyword_annihilation  keyword_apocalypse  keyword_armageddon  \
0                      0.0                 0.0                 0.0   
1                      0.0                 0.0                 0.0   
2                      0.0                 0.0                 0.0   
3                      0.0                 0.0                 0.0   
4                      0.0                 0.0                 0.0   
...                    ...                 ...                 ...   
7608                   0.0                 0.0                 0.0   
7609                   0.0                 0.0                 0.0   
7610                   0.0                 0.0                 0.0   
7611                   0.0                 0.0                 0.0   
7612                   0.0                 0.0                 0.0   

      keyword_army  ...  keyword_weapons  keyword_whirlwind  \
0              0.0  ...              0.0                0.0   
1              0.0  ...              0.0                0.0   
2              0.0  ...              0.0                0.0   
3              0.0  ...              0.0                0.0   
4              0.0  ...              0.0                0.0   
...            ...  ...              ...                ...   
7608           0.0  ...              0.0                0.0   
7609           0.0  ...              0.0                0.0   
7610           0.0  ...              0.0                0.0   
7611           0.0  ...              0.0                0.0   
7612           0.0  ...              0.0                0.0   

      keyword_wild fires  keyword_wildfire  keyword_windstorm  \
0                    0.0               0.0                0.0   
1                    0.0               0.0                0.0   
2                    0.0               0.0                0.0   
3                    0.0               0.0                0.0   
4                    0.0               0.0                0.0   
...                  ...               ...                ...   
7608                 0.0               0.0                0.0   
7609                 0.0               0.0                0.0   
7610                 0.0               0.0                0.0   
7611                 0.0               0.0                0.0   
7612                 0.0               0.0     

In [547]:
X= train_1
y = data['target']

In [548]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [549]:
ss = StandardScaler()

X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [550]:
bnb = BernoulliNB()

In [551]:
bnb.fit(X_train,y_train)

BernoulliNB()

In [552]:
bnb.score(X_train,y_train)

0.7500821018062397

In [553]:
bnb.score(X_test,y_test)

0.7137229152987524

In [474]:
train_1.shape

(7613, 222)

In [475]:
data[['text']].shape

(7613, 1)

In [476]:
train = train_1.join(data[['text']],how = 'right')

In [477]:
train.head(2)

keyword_ablaze  keyword_accident  keyword_aftershock  \
0             0.0               0.0                 0.0   
1             0.0               0.0                 0.0   

   keyword_airplane accident  keyword_ambulance  keyword_annihilated  \
0                        0.0                0.0                  0.0   
1                        0.0                0.0                  0.0   

   keyword_annihilation  keyword_apocalypse  keyword_armageddon  keyword_army  \
0                   0.0                 0.0                 0.0           0.0   
1                   0.0                 0.0                 0.0           0.0   

   ...  keyword_whirlwind  keyword_wild fires  keyword_wildfire  \
0  ...                0.0                 0.0               0.0   
1  ...                0.0                 0.0               0.0   

   keyword_windstorm  keyword_wounded  keyword_wounds  keyword_wreck  \
0                0.0              0.0             0.0            0.0   
1                0.0              0.0             0.0            0.0   

   keyword_wreckage  keyword_wrecked  \
0               0.0              0.0   
1               0.0              0.0   

                                                text  
0  Our Deeds are the Reason of this  earthquake M...  
1             Forest fire near La Ronge Sask. Canada  

[2 rows x 223 columns]

In [478]:
data['text']

0       Our Deeds are the Reason of this  earthquake M...
1                  Forest fire near La Ronge Sask. Canada
2       All residents asked to 'shelter in place' are ...
3       13,000 people receive  wildfires evacuation or...
4       Just got sent this photo from Ruby  Alaska as ...
                              ...                        
7608    Two giant cranes holding a bridge collapse int...
7609    @aria_ahrary @TheTawniest The out of control w...
7610    M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...
7611    Police investigating after an e-bike collided ...
7612    The Latest: More Homes Razed by Northern Calif...
Name: text, Length: 7613, dtype: object

In [499]:
# Define a Series with multiple inputs
texts = pd.Series(data['text'])

In [500]:
texts = cvec.transform(texts)

In [501]:
texts = texts.todense()

In [519]:
texts

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [502]:
df2 = pd.DataFrame(texts)

In [503]:
name = []
for i in range(0,21596):
    name.append(str(i)+'_'+'val')

In [504]:
df2.columns =name

In [505]:
train_new = train.join(df2,how = 'right')

In [506]:
train_new

keyword_ablaze  keyword_accident  keyword_aftershock  \
0                0.0               0.0                 0.0   
1                0.0               0.0                 0.0   
2                0.0               0.0                 0.0   
3                0.0               0.0                 0.0   
4                0.0               0.0                 0.0   
...              ...               ...                 ...   
7608             0.0               0.0                 0.0   
7609             0.0               0.0                 0.0   
7610             0.0               0.0                 0.0   
7611             0.0               0.0                 0.0   
7612             0.0               0.0                 0.0   

      keyword_airplane accident  keyword_ambulance  keyword_annihilated  \
0                           0.0                0.0                  0.0   
1                           0.0                0.0                  0.0   
2                           0.0                0.0                  0.0   
3                           0.0                0.0                  0.0   
4                           0.0                0.0                  0.0   
...                         ...                ...                  ...   
7608                        0.0                0.0                  0.0   
7609                        0.0                0.0                  0.0   
7610                        0.0                0.0                  0.0   
7611                        0.0                0.0                  0.0   
7612                        0.0                0.0                  0.0   

      keyword_annihilation  keyword_apocalypse  keyword_armageddon  \
0                      0.0                 0.0                 0.0   
1                      0.0                 0.0                 0.0   
2                      0.0                 0.0                 0.0   
3                      0.0                 0.0                 0.0   
4                      0.0                 0.0                 0.0   
...                    ...                 ...                 ...   
7608                   0.0                 0.0                 0.0   
7609                   0.0                 0.0                 0.0   
7610                   0.0                 0.0                 0.0   
7611                   0.0                 0.0                 0.0   
7612                   0.0                 0.0                 0.0   

      keyword_army  ...  21586_val  21587_val  21588_val  21589_val  \
0              0.0  ...          0          0          0          0   
1              0.0  ...          0          0          0          0   
2              0.0  ...          0          0          0          0   
3              0.0  ...          0          0          0          0   
4              0.0  ...          0          0          0          0   
...            ...  ...        ...        ...        ...        ...   
7608           0.0  ...          0          0          0          0   
7609           0.0  ...          0          0          0          0   
7610           0.0  ...          0          0          0          0   
7611           0.0  ...          0          0          0          0   
7612           0.0  ...          0          0          0          0   

      21590_val  21591_val  21592_val  21593_val  21594_val  21595_val  
0             0          0          0          0          0          0  
1             0          0          0          0          0          0  
2             0          0          0          0          0          0  
3             0          0          0          0          0          0  
4             0          0          0          0          0          0  
...         ...        ...        ...        ...        ...        ...  
7608          0          0          0          0          0          0  
7609          0          0          0          0          0          0  
7610     

In [507]:
X = train_new
y=data['target']

In [508]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [509]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6090 entries, 4996 to 7270
Columns: 21819 entries, keyword_ablaze to 21595_val
dtypes: float64(222), int64(21596), object(1)
memory usage: 1013.8+ MB


In [510]:
ss = StandardScaler()

X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

ValueError: could not convert string to float: 'Courageous and honest analysis of need to use Atomic Bomb in 1945.  Hiroshima70 Japanese military refused surrender. https: t.co/VhmtyTptGR'

In [493]:
bnb = BernoulliNB()

In [494]:
bnb.fit(X_train,y_train)

ValueError: could not convert string to float: 'Courageous and honest analysis of need to use Atomic Bomb in 1945.  Hiroshima70 Japanese military refused surrender. https: t.co/VhmtyTptGR'

In [285]:
bnb.score(X_train,y_train)

0.8973727422003284

In [286]:
bnb.score(X_test,y_test)

0.804333552199606

0    1
1    2
2    3
Name: Series1, dtype: int64

In [240]:
df

TextFeature CategoryFeature  NumericFeature  Target
0  This is a sample text.               A               1       1
1   Another example text.               B               2       0
2  Text data for testing.               A               3       1
3         More text data.               C               4       0

In [497]:
import gensim